### ISSUE TITLE
Flaw in the running process check

### ISSUE THREAD

**Issue by vdemonchy** [nalipaz/poll-xrandr#1]
Hello,

I think there is a flaw in the way you check if poll-xrandr is already running : you check if the process is running inside the process himself, so the test always fail for obvious reasons.

**Comment by nalipaz** [comment]
You are right, I think that needs to be removed or rewritten slightly.  I will fix it.  Thanks for reporting it.

**Comment by vdemonchy** [comment]
I think you can use [pidof](http://linux.die.net/man/8/pidof) instead by doing `$(pidof -x poll-xrandr -o %PPID)`. It will return the PID of an already running poll-xrandr script but will omit the parent process running pidof, which is exactly what we want to achieve here. If there is no already running poll-xrandr, nothing is returned.

I've tested this method and it seems to work fine :)

**Comment by nalipaz** [comment]
I have committed the aforementioned fix, please let me know if it doesn't fix or I implemented wrong.  I didn't have the time to test at the moment of adding it.  I will release once you can confirm and I have a chance to test it.

**Comment by nalipaz** [comment]
I am assuming this is fixed, I haven't noticed any issues on my end.
